/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // leftSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  leftSidebar: [
    'intro',
    'contact',
    'feedback',
    { // we define the category folders here so we do not need to add _category_.json files to each directory
      type: 'category',
      label: 'JoCo Study Basics',
      "link": {
        "type": "generated-index",
        "description": "If you are new to the JoCo data this is the place to start to learn more about the data that is available."
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'jocoknow-basics', // Generate sidebar slice from docs/tutorials/easy
        },
      ]
    },
    { // for the datasets we want one file that lists the descriptions of the datasets and links to the resources since having left menu links is confusing and provide little context or information
      // type: 'doc',
      // id: 'datasets/dataset-list',
      label: 'Datasets',
      type: 'category',
      "link": {
        "type": "generated-index",
        "description": "This section contains a list of datasets published to a public repository."
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'datasets',
        },
      ]
      // items: [
      //   {
      //     type: 'doc',
      //     id: 'datasets/dataset-list',
      //   },
      // ]
    },
    { 
      type: 'category',
      label: "Data Curation Tools",
      "link": {
        "type": "generated-index",
        "description": "We want to help you manage your data as well as we have, by providing you with the toolset we used to manage this project."
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'curation-tools',
        },
      ]
    },
  ],
};

export default sidebars;